- name: Apply basic config to all systems
  hosts: webserver, database
  user: root
  roles:
    - common

- name: Install MySQL on databases
  hosts: database
  user: root
  roles:
    - database

- name: Install Apache2 on webservers
  hosts: webserver
  user: root
  roles:
    - webserver
