---
# Install Logstash dependencies
- name: "Install Logstash dependencies"
  sudo: yes
  action: apt pkg={{ item }} state=installed update_cache=yes
  with_items: logstash.deb.dependencies

# Create Logstash destination
- name: "Create Logstash directories"
  sudo: yes
  action: file path={{ item }} group=root owner=root mode=0755 state=directory
  with_items:
    - '{{ logstash.dir }}'
    - '{{ logstash.dir }}/bin'
    - '{{ logstash.dir }}/etc'

# Install Logstash indexer init script
- name: "Install Logstash indexer init script"
  sudo: yes
  action: template src=logstash_indexer.j2 dest=/etc/init.d/{{ logstash.indexer.service }} owner=root group=root mode=0755
# old logstash_indexer.j2 
  when: with_indexer

# Install Logstash shipper init script
- name: "Install Logstash shipper init script"
  sudo: yes
  action: template src=logstash_shipper.j2 dest=/etc/init.d/{{ logstash.shipper.service }} owner=root group=root mode=0755
  when: with_shipper

# Install Logstash indexer config
- name: "Install Logstash indexer config"
  sudo: yes
  action: template src=logstash_indexer.conf.j2 dest={{ logstash.indexer.conf }} owner=root group=root mode=0755
  when: with_indexer
  notify:
    - "Restart Logstash indexer"

# Install Logstash shipper config
- name: "Install Logstash shipper config"
  sudo: yes
  action: template src=logstash_shipper.conf.j2 dest={{ logstash.shipper.conf }} owner=root group=root mode=0755
  when: with_shipper
  register: shipper_config
  notify:
    - "Restart Logstash shipper"

# Fetch Logstash JAR
- name: "Fetch Logstash"
  sudo: yes
  get_url: url={{ logstash.url }}/{{ logstash.jar }} dest={{ logstash.dir }}/bin thirsty=yes mode=0440
  register: get_jar

# Start Logstash indexer
- name: "Start Logstash indexer"
  sudo: yes
  action: service name={{ logstash.indexer.service }} state=started
  when: with_indexer

# Start Logstash shipper
- name: "Start Logstash shipper"
  sudo: yes
  action: service name={{ logstash.shipper.service }} state=started
  when: with_shipper

